version: '3'
services:
        test-1:
                image: mysql
                build: .
                ports:
                        - "1020:1020"
        
        test-2: 
                image: mysql
                build: .
                ports:
                        - "1021:1021"

        test-3:
                image: mysql
                build: .
                ports:
                        - "1022:1022"
